services:
    wildledger_db:
        image: postgres
        container_name: wildledger_db

        ports:
            - "5432:5432"

        env_file: "./.env"

    wildledger_cache:
        image: redis:7-alpine
        container_name: wildledger_cache

        ports:
            - "6379:6379"

        env_file: "./.env"

    wildledger_s3:
        image: minio/minio:latest
        container_name: wildledger_s3

        ports:
            - "9000:9000"
            - "9001:9001"
        
        env_file: "./.env"

        volumes:
            - ./init_s3.sh:/scripts/init_s3.sh
        entrypoint: ["/bin/sh", "/scripts/init_s3.sh"]