spring:
    application:
        name: wildledger
    profiles:
        active: prod

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false

    data:
        redis:
            timeout: 60000

server:
    servlet:
        context-path: /api/0.1.0

app:
    rate-limit:
        max-requests-per-minute: 10
        window-ms: 60000

    s3:
        endpoint: http://${MINIO_HOST}:${MINIO_PORT}
        access-key: ${MINIO_USER}
        secret-key: ${MINIO_PASSWORD}
        bucket: sightings
        region: us-east-1

jwt:
    secret: ${JWT_SECRET:myDefaultSecretKey12345678901234567890}
    expiration: 900000
    refresh-expiration: 604800000

logging:
    level:
        root: INFO
        com.gen-4.wildledger: DEBUG
        org.springframework.security: DEBUG