spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:changeme}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 300000

    sql:
        init:
            mode: always

    data:
        redis:
            host: localhost
            port: 6379
            password: ${REDIS_PASSWORD:}

    flyway:
        enabled: false

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        defer-datasource-initialization: true
        
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

app:
    storage:
        max-file-size: 10000

logging:
  level:
    root: INFO
    com.gen-4.wildledger: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
